.TH neptune 1
.SH NAME
neptune - Print a salutation from Neptune

.SH SYNOPSIS
.B neptune

.SH DESCRIPTION
.B neptune
Print a salutation from Neptune

.SH EXAMPLES
.TP
\fBneptune\fR
Prints a salutation from planet Neptune

.SH EXIT STATUS
EXIT STATUS
neptune exits with status 0 if the salutation is processed successfully,
greater than 0 if errors occur.
