name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Test all make targets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-plt
        with:
          path: ./tests/neptune.plt
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Build and test
        run: |
          set -xv
          erl +B -noinput -eval 'io:put_chars(erlang:system_info(system_version)),halt(0).'
          ./bootstrap.sh
          ./configure --prefix=/usr
          make
          # Use cached ./tests/neptune.plt
          make check

      - name: Install and check installation
        run: |
          make install DESTDIR=$PWD/inst
          # Use cached ./tests/neptune.plt
          sudo make installcheck DESTDIR=$PWD/inst

      - name: Build and test distribution tarball
        run: |
          make dist
          # Not possible to use cached ./tests/neptune.plt
          make distcheck
