name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Test all make targets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-plt
        with:
          path: ./tests/neptune.plt
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Bootstrap
        run: |
          set -xv
          erl +B -noinput -eval 'io:put_chars(erlang:system_info(system_version)),halt(0).'
          sudo apt-get update -y
          sudo apt-get install -y xsltproc 
          ./bootstrap.sh
          
      - name: Configure
        run:
          ./configure --prefix=/usr

      - name: Build
        run:
          make V=1

      - name: Test
        run:
          # Use cached ./tests/neptune.plt
          make check V=1 TESTSUITEFLAGS=-v

      - name: Install
        run:
          make install DESTDIR=$PWD/inst V=1

      - name: Install Check
        run:
          # Use cached ./tests/neptune.plt
          sudo make installcheck DESTDIR=$PWD/inst V=1 TESTSUITEFLAGS=-v

      - name: Build and test distribution tarball
        run: |
          make dist V=1
          # Not possible to use cached ./tests/neptune.plt
          make distcheck V=1 TESTSUITEFLAGS=-v
