name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Test all make targets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build and test
        run: |
          set -xv
          erl +B -noinput -eval 'io:put_chars(erlang:system_info(system_version)),halt(0).'
          ./bootstrap.sh
          ./configure --prefix=/usr
          make
          make check

      - name: Install and check installation
        run: |
          make install DESTDIR=$PWD/inst
          make installcheck DESTDIR=$PWD/inst
                - name: Install and check installation

      - name: Build and test distribution tarball
        run: |
          make dist
          make distcheck
