name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Test all make targets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # TODO: cache neptune.plt
      
      - name: Build and test
        run: |
          set -xv
          erl +B -noinput -eval 'io:put_chars(erlang:system_info(system_version)),halt(0).'
          ./bootstrap.sh
          ./configure --prefix=/usr
          make
          make check

      - name: Install and check installation
        run: |
          make install DESTDIR=$PWD/inst
          # TODO: sudo rights needed to run installcheck
          # make installcheck DESTDIR=$PWD/inst

      - name: Build and test distribution tarball
        run: |
          make dist
          # TODO: sudo rights needed to run distcheck
          # make distcheck
